# This workflow is managed by gh actions-lock.

on:
  push:

jobs:
  basic:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Echo
        uses: $/.github/actions/echo
